ARG FROM

FROM $FROM

USER root

RUN apt-get update \
 && apt-get install -y libfontconfig1 libxrender1 libxtst6 libxi6 libsecret-1-0 gnome-keyring \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN wget https://download.jetbrains.com/rider/JetBrains.Rider-2020.2.3.tar.gz \
 && tar xzf JetBrains.Rider-2020.2.3.tar.gz \
 && rm JetBrains.Rider-2020.2.3.tar.gz

RUN ln -s /opt/JetBrains\ Rider-2020.2.3/bin/rider.sh /usr/bin/rider

USER ${IMAGE_USER}
WORKDIR /home/${IMAGE_USER}

CMD ["rider"]
