ARG FROM

FROM $FROM

USER root

RUN apt-get update \
 && apt-get install -y vim firefox \
 && rm -rf /var/lib/apt/lists/*

ARG FIREFOX=/usr/lib/firefox/firefox
RUN mv ${FIREFOX} ${FIREFOX}_no_flags \
 && echo "#! /bin/bash" > ${FIREFOX} \
 && echo "${FIREFOX}_no_flags --no-remote \"\$@\"" >> ${FIREFOX} \
 && chmod +x ${FIREFOX}

USER ${IMAGE_USER}
WORKDIR /home/${IMAGE_USER}

CMD ["bash"]
